### PR TITLE
Take array initialization outside of the bench loop

### PR DESCRIPTION
**Pull request by mourner**
Makes benchmarks slightly more predictable.

### CODE REVIEW

**Comment by rowanwins** [comment]
Thanks @mourner , will update the readme later this evening when I'm back at home.

**Comment by rowanwins** [comment]
Gday @mourner 

Well with this change `lineclip` outperforms `kwc-lineclip` on longer lines, although I'm a bit confused why the previous benchmark was showing differently given that both tests were being performed the same way previously 🤷 ?

````
SINGLE SEGMENT TEST
kwc x 10,002,696 ops/sec ±3.20% (85 runs sampled)
liang-barsky (non-destructive) x 17,297,695 ops/sec ±4.66% (84 runs sampled)
mapbox/lineclip x 6,591,552 ops/sec ±3.37% (76 runs sampled)
- Fastest is liang-barsky (non-destructive)

MULTIPLE SEGMENT MULTIPLE OUTPUT TEST
kwc x 5,436,613 ops/sec ±3.80% (76 runs sampled)
mapbox/lineclip x 3,682,985 ops/sec ±2.89% (84 runs sampled)
- Fastest is kwc

LONGER LINE
kwc x 1,674,973 ops/sec ±1.27% (90 runs sampled)
mapbox/lineclip x 1,877,809 ops/sec ±0.52% (93 runs sampled)
- Fastest is mapbox/lineclip

ANOTHER LONG LINE TEST
kwc x 650,720 ops/sec ±0.45% (95 runs sampled)
mapbox/lineclip x 955,607 ops/sec ±0.55% (94 runs sampled)
- Fastest is mapbox/lineclip
````
I suspect there would be room to optimise this algorithm further although I don't have any really compelling to do so (other than pride!) at the moment so perhaps one day when I'm feeling inspired.

**Comment by mourner** [comment]
>  I'm a bit confused why the previous benchmark was showing differently given that both tests were being performed the same way previously 🤷 ?

I have no explanation for that too, but generally I've found microbenchmarks (where a very small task is repeated a few million times) to be very unreliable on modern JS engines. The best way to benchmark is usually to take a huge set of real world data and run a realistic task that doesn't process the same feature more than once.

**Comment by rowanwins** [comment]
That's good to know, I'll give that a whirl and see if that makes any difference.

**Pull request merged**
